default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: homebrew-heroes_development
  username: postgres
  password: ''
  host: localhost

test:
  <<: *default
  database: homebrew-heroes_test
  username: postgres
  password: ''
  host: localhost

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
